name: 'Publish Artifact'
description: 'Publish an artifact for a GitHub Actions workflow'
inputs:
  name:
    description: 'The name of the artifact will be published under'
    required: true
    default: 'infrastructure'
  path:
    description: 'The path to the artifact to publish'
    required: true
    default: 'infrastructure'
  if-no-files-found:
    description: 'What to do if no files are found at the specified path'
    required: true
    default: 'error'

runs:
  using: composite
  steps: 

  # Save plan to artifacts  
  - name: Publish Terraform Plan
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.name }}
      if-no-files-found: ${{ inputs.if-no-files-found }}
      path: ${{ inputs.path }}