name: 'Terraform Configuration Deploy'
on:
    workflow_call:
      inputs:
        environment:
          description: 'Environment Name'
          required: true
          type: string


jobs:
  terraform-deploy:
    name: 'Terraform Deploy ${{inputs.environment}}'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
    permissions:
        id-token: write # Require write permission to Fetch an OIDC token.
        contents: read
    #These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
    env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true       
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    - id: publish-infrastructure
      uses: './.github/jobs/tf-apply'
      with:
        environmentName: 'dev'
        backendResourceGroupName: ${{ vars.BACKEND_RESOURCE_GROUP_NAME}}
        backendStorageAccountName: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
        backendStorageContainerName: ${{ vars.BACKEND_STORAGE_CONTAINER_NAME }}




        
        

    
