name: 'Terraform Configuration Build'
on: push

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_USE_OIDC: true

jobs:
  terraform-build-dev:
    name: 'Terraform Build Dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    - id: publish-infrastructure
      uses: './.github/jobs/tf-plan'
      with:
        environmentName: 'dev'
        backendResourceGroupName: ${{ vars.BACKEND_RESOURCE_GROUP_NAME}}
        backendStorageAccountName: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
        backendStorageContainerName: ${{ vars.BACKEND_STORAGE_CONTAINER_NAME }}
  terraform-build-tst:
    name: 'Terraform Build Tst'
    runs-on: ubuntu-latest
    environment: tst
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    - id: publish-infrastructure
      uses: './.github/jobs/tf-plan'
      with:
        environmentName: 'tst'
        backendResourceGroupName: ${{ vars.BACKEND_RESOURCE_GROUP_NAME}}
        backendStorageAccountName: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
        backendStorageContainerName: ${{ vars.BACKEND_STORAGE_CONTAINER_NAME }}
                      
  terraform-ci:
      name: 'Terraform CI Checks'
      runs-on: ubuntu-latest
      steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      - id: terraform-ci-check
        uses: './.github/jobs/tf-ci-check'
  infrastructure-publish:
    runs-on: ubuntu-latest
    name: 'Publish Infrastructure'
    steps:
      - uses: actions/checkout@v4
      - id: publish-infrastructure
        uses: './.github/jobs/upload-artifact-job'
        with:
          name: 'infrastructure'
          path: './infrastructure'
  terraform-deploy-dev:
    runs-on: ubuntu-latest
    name: terraform-deploy-dev
    needs: 
      - terraform-ci
      - infrastructure-publish
      - terraform-build-dev
      - terraform-build-tst
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Apply Terraform
        uses: ./.github/workflows/tf-apply.yml
        with:
          environment: "dev"



        
        

    
